full_sign_up_profile_info = {
    "tile_dropdown" : "Ms",
    "map(firstName)" : "First Name John",
    "map(lastName)" : "Sur Name Smith",
    "map(dobDay)" : "20",
    "map(dobMonth)" : "07",
    "map(dobYear)" : "1920",
    "map(email)" : "karen@test.com",
    "map(phone)" : "3023021234",
    "map(mobile)" : "7864267890",
    "map(address1)" : "123 Gan St.",
    "map(address2)" : "Apt# 302",
    "map(addressCity)" : "Miami",
    "map(stateProv)" : "Miami Dade",
    "map(postCode)" : "330127",
    "countryList" : "GA",
    "map(userName)" : "kgantest",
    "password" : "Testpassword1!",
    "map(passwordConfirm)" : "Testpassword1!",
    "map(securityQuestionOne)" : "In what city or town was your first job?",
    "map(securityAnswerOne)" : "Wynwood",
    "map(securityQuestionTwo)" : "What is your favorite color?",
    "map(securityAnswerTwo)" : "Pink",
    "map(currency)" : "USD",
}